num1=int (input("Enter first number : "))
num2 = int (input("Enter seceon number : "))
print("You have entered ", num1 ,num2)
print('sum : ',num1 + num2)
print('Difference : ',num1 - num2)
print('Division' ,num1 // num2)
print('Reminder :',num1 % num2)
print("Product : ",num1 * num2)
# print(num1 ** num2)